### ISSUE TITLE
Mark as inactive on OBO Foundry

### ISSUE THREAD

**Issue by cthoyt** [linikujp/OGSF#2]
Hi @linikujp, given there haven't been any changes on this ontology for 8 years, can we mark it as inactive on the OBO Foundry list?

**Comment by linikujp** [comment]
Hi Charlie,

Thank you for asking! If mark it as inactive, it should not affect people to check it out, right? 

Thanks,
Asiyah

**Comment by cthoyt** [comment]
It's still listed in the OBO Foundry. It just is a useful piece of information for people to know that it's not actively being updated

**Comment by linikujp** [comment]
Sure. I think it is fine to list as "inactive".
